// Generated by prisma/post-generate.ts
import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { customAlphabet } from "nanoid";

const sqlite = new Database("sqlite.db");
export const db: BunSQLiteDatabase = drizzle(sqlite);

export * from "./drizzle/types";
export * from "./drizzle/enums";

// Use custom alphabet without special chars for less chaotic, copy-able URLs
// Will not collide for a long long time: https://zelark.github.io/nano-id-cc/
export const genId = customAlphabet("0123456789abcdefghijklmnopqrstuvwxyz", 16);
